spring:
  datasource:
    url: jdbc:mysql://localhost:3306/amazon_InnoDB?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: wechatdemo
#logging:
#  file: D:\workSource\logFromWechatDemo\WechatDemo.log

wechat:
  openAppId: wx71dc347e2710f151
  openAppSecret: nYaKLWbEtNg9ICMI4KVUcXTT2hg3GSlB
server:
  port: 2080

